#!/bin/bash
# COLOR VALIDATION
clear
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
###########- COLOR CODE -##############
colornow=$(cat /etc/yudhynetwork/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m" 
COLOR1="$(cat /etc/yudhynetwork/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/yudhynetwork/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"    
WH='\033[1;37m'
UPDATE="https://raw.githubusercontent.com/driwwstore/project/main/"
BOT="https://raw.githubusercontent.com/driwwstore/project/main/"


echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}              ${WH}• PANEL BOT NOTI •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
echo -e "$COLOR1 ${NC}  ${WH}[${COLOR1}01${WH}]$NC ${COLOR1}• ${WH}Agregar Bot Notificacion${NC}"
echo -e "$COLOR1 ${NC}  ${WH}[${COLOR1}02${WH}]$NC ${COLOR1}• ${WH}Eliminar Bot${NC}"
echo -e "$COLOR1 ${NC}  ${WH}[${COLOR1}03${WH}]$NC ${COLOR1}• ${WH}GO BACK${NC}"
echo -e "\e[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
read -p "  Select From Options [ 1 - 2 or 0 ] : " menu
case $menu in
1 | 01) clear ;
    add-bot-notif
    ;;
2 | 02) clear ;
    del-bot-notif
    ;;
3 | 03) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac
