#!/bin/bash
# SL
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
# ==========================================
clear
echo " "
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo " ";
if [ -e "/root/log-limit.txt" ]; then
echo "Usuario que viola el límite máximo";
echo "Hora - Nombre de usuario - Número de inicios de sesión múltiples"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
cat /root/log-limit.txt
else
echo " Ningún usuario ha cometido una infracción."
echo " "
echo " or"
echo " "
echo " El script de límite de usuarios no se ha ejecutado."
fi
echo " ";
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo " ";
read -n 1 -s -r -p "Presione cualquier tecla para regresar al menú"

m-sshws
 
