#!/bin/bash
dateFromServer=$(curl -v --insecure --silentmenu9ps://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
        echo -e "\e[42m             Delete Vmess Account        \E[0m"
        echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
		echo ""
		echo "No tienes clientes existentes!"
		echo ""
		echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
		read -n 1 -s -r -p "Presione cualquier tecla para regresar al menú"
        m-vmess
	fi

	clear
	echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "\e[42m             Delete Vmess Account        \E[0m"
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo ""
	grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""
    red "Tap enter to go back"
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
	read -rp "Input Username : " user
    if [ -z $user ]; then
    m-vmess
    else
    exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
    systemctl restart xray > /dev/null 2>&1
    clear
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "\e[42m    Vmess Account Deleted Successfully   \E[0m"
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo ""
    echo " Nombre del cliente : $user"
    echo " Expirado el  : $exp"
    echo ""
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo ""
    read -n 1 -s -r -p "Presione cualquier tecla para regresar al menú"
    m-vmess
    fi
