#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
###########- COLOR CODE -##############
colornow=$(cat /etc/yudhynetwork/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m" 
COLOR1="$(cat /etc/yudhynetwork/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/yudhynetwork/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')" 
WH='\033[1;37m'    
# Getting
export CHATID="1210833546"
export KEY="6006599143:AAEgstCAioq35JgX97HaW_G3TAkLKzLZS_w"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear

echo -e "\e[32mloading...\e[0m"
clear
#Domain
domain=$(cat /etc/xray/domain)

function lock(){
clear
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}            ${WH}• BLOQUEAR USUARIOS SSH •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
read -p "Escribe el usuario: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
passwd -l $username
clear
  echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}             ${WH}• BLOQUEO USER EXISTOSO •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"

echo " "
  echo -e "Username ${blue}$username${NC} Successfully ${red}LOCKED!${NC}."
  echo -e "Akses Login to username ${blue}$username${NC} has been locked."
  echo " "
  echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
else
echo "Nombre de usuario no encontrado en su servidor."
    exit 1
fi
read -n 1 -s -r -p "Presione cualquier tecla para regresar al menú"
menu
}

function unlock(){
clear
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}            ${WH}• DESBLOQUEAR USUARIO SSH•              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
read -p "Input Username: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
passwd -u $username
clear
  echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}            ${WH}• DESBLOQUEO SSH EXITOSO •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
 echo " "
  echo -e "Username ${blue}$username${NC} Successfully ${green}UNLOCKED${NC}."
  echo -e "Nombre de usuario ${blue}$username${NC} ha sido restaurado"
  echo " "
  echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
else
echo " "
echo -e "Username ${red}$username${NC} not found in your server."
echo " "    
	exit 1
fi
read -n 1 -s -r -p "Presione cualquier tecla para regresar al menú"
menu
}
clear
echo -e "$COLOR1┌─────────────────────────────────────────────────┐${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}               ${WH}• SSH PANEL MENU •              ${NC} $COLOR1 $NC"
echo -e "$COLOR1└─────────────────────────────────────────────────┘${NC}"
echo -e " $COLOR1┌───────────────────────────────────────────────┐${NC}
 $COLOR1 $NC   ${WH}[${COLOR1}01${WH}]${NC} ${COLOR1}• ${WH}AGREGAR SSH         ${WH}[${COLOR1}08${WH}]${NC} ${COLOR1}• ${WH}USERS MULTILOGIN${NC}    $COLOR1 $NC
 $COLOR1 $NC   ${WH}[${COLOR1}02${WH}]${NC} ${COLOR1}• ${WH}RENOVAR SSH         ${WH}[${COLOR1}09${WH}]${NC} ${COLOR1}• ${WH}BLOQUEAR USUARIOS${NC}     $COLOR1 $NC
 $COLOR1 $NC   ${WH}[${COLOR1}03${WH}]${NC} ${COLOR1}• ${WH}USUARIOS ONLINE     ${WH}[${COLOR1}10${WH}]${NC} ${COLOR1}• ${WH}DESBLOQUEAR USUARIOS${NC}    $COLOR1 $NC
 $COLOR1 $NC   ${WH}[${COLOR1}04${WH}]${NC} ${COLOR1}• ${WH}LISTA DE USUARIOS       $COLOR1 $NC
 $COLOR1 $NC   ${WH}[${COLOR1}05${WH}]${NC} ${COLOR1}• ${WH}ELIMINAR USUARIOS
 $COLOR1 $NC   ${WH}[${COLOR1}06${WH}]${NC} ${COLOR1}• ${WH}ELIMINAR USER EXPIRADOS
 $COLOR1 $NC   ${WH}[${COLOR1}07${WH}]${NC} ${COLOR1}• ${WH}AUTO KILL
$COLOR1 $NC                                              ${NC} $COLOR1 $NC
 $COLOR1 $NC   ${WH}[${COLOR1}00${WH}]${NC} ${COLOR1}• ${WH}GO BACK${NC}                              $COLOR1 $NC"
echo -e " $COLOR1└───────────────────────────────────────────────┘${NC}" 
echo -e""
read -p "Select From Options [ 01 - 11 ] : " menu
case $menu in
1 | 01)
    addssh
    ;;
2 | 02)
    renewssh
    ;;
3 | 03)
    cekssh
    ;;
4 | 04)
    member
    ;;
5 | 05)
    delssh
    ;;
6 | 06)
    delexp
    ;;
7 | 07)
    autokill
    ;;
8 | 08)
    ceklim
    ;;
9 | 09)
    lock
    ;;
10)
    unlock
    ;;
11)
    menu
    ;;
*)
echo -e ""
echo -e "Lu Salah Tekan Gblok"
sleep 1
m-sshws
;;
esac
