#!/bin/bash
clear; sleep 1
echo -e " __          __  _                            "; sleep .1
echo -e " \ \        / / | |                           "; sleep .1
echo -e "  \ \  /\  / ___| | ___ ___  _ __ ___   ___   "; sleep .1
echo -e "   \ \/  \/ / _ | |/ __/ _ \| ,_ , _ \ / _ \  "; sleep .1
echo -e "    \  /\  |  __| | (_| (_) | | | | | |  __/  "; sleep .1
echo -e "     \/  \/ \___|_|\___\___/|_| |_| |_|\___]  "; sleep .1
